# Generated by Django 5.2.16 on 2026-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_signature",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="경로 시그니처",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="이동 수단"
                    ),
                ),
                (
                    "hour_bucket",
                    models.SmallIntegerField(default=-1, verbose_name="시간대(시)"),
                ),
                (
                    "weekday_type",
                    models.CharField(
                        choices=[
                            ("weekday", "평일"),
                            ("weekend", "주말"),
                            ("any", "구분 없음"),
                        ],
                        default="any",
                        max_length=8,
                        verbose_name="요일 구분",
                    ),
                ),
                ("factor", models.FloatField(default=1.0, verbose_name="보정 계수")),
                (
                    "sd_minutes",
                    models.FloatField(default=0.0, verbose_name="잔차 표준편차(분)"),
                ),
                (
                    "sample_count",
                    models.PositiveIntegerField(default=0, verbose_name="표본 수"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="갱신 시각"),
                ),
            ],
            options={
                "verbose_name": "경로 보정",
                "verbose_name_plural": "경로 보정",
                "db_table": "routing_route_correction",
                "ordering": ["route_signature", "mode", "hour_bucket"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "route_signature",
                            "mode",
                            "hour_bucket",
                            "weekday_type",
                        ),
                        name="routing_correction_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("factor__gte", 0.25), ("factor__lte", 4.0)),
                        name="routing_correction_factor_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sd_minutes__gte", 0)),
                        name="routing_correction_sd_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("hour_bucket__gte", -1), ("hour_bucket__lte", 23)
                        ),
                        name="routing_correction_hour_range",
                    ),
                ],
            },
        ),
    ]
