# Generated by Django 5.2.16 on 2026-09-22 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "events",
            "0004_event_origin_label_event_origin_lat_event_origin_lng_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="이름")),
                (
                    "default_min_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(480),
                        ],
                        verbose_name="최소 소요(분)",
                    ),
                ),
                (
                    "default_max_minutes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(480),
                        ],
                        verbose_name="최대 소요(분)",
                    ),
                ),
                (
                    "drop_cost",
                    models.CharField(
                        choices=[
                            ("none", "없음 (건너뛰어도 무관)"),
                            ("small", "작음"),
                            ("medium", "보통"),
                            ("large", "큼"),
                            ("impossible", "불가 (반드시 해야 함)"),
                        ],
                        default="medium",
                        max_length=12,
                        verbose_name="포기 시 손실",
                    ),
                ),
                (
                    "parallelizable",
                    models.BooleanField(default=False, verbose_name="병렬 가능"),
                ),
                (
                    "included_by_default",
                    models.BooleanField(default=True, verbose_name="기본 포함"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "precondition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="routines.routineblock",
                        verbose_name="선행 블록",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "루틴 블록",
                "verbose_name_plural": "루틴 블록",
                "db_table": "routines_block",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventBlockSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked", models.BooleanField(default=True, verbose_name="포함")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_selections",
                        to="events.event",
                        verbose_name="일정",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="routines.routineblock",
                        verbose_name="블록",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정별 블록 선택",
                "verbose_name_plural": "일정별 블록 선택",
                "db_table": "routines_event_block_selection",
            },
        ),
        migrations.CreateModel(
            name="BlockObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_on", models.DateField(verbose_name="관측 날짜")),
                (
                    "duration_minutes",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(480),
                        ],
                        verbose_name="실제 소요(분)",
                    ),
                ),
                (
                    "slack_minutes",
                    models.FloatField(
                        blank=True, null=True, verbose_name="가용 여유(분)"
                    ),
                ),
                (
                    "was_parallel",
                    models.BooleanField(default=False, verbose_name="병렬로 진행"),
                ),
                (
                    "client_uuid",
                    models.CharField(max_length=40, verbose_name="클라이언트 UUID"),
                ),
                (
                    "client_recorded_at",
                    models.DateTimeField(verbose_name="앱 기록 시각"),
                ),
                (
                    "server_received_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="서버 수신 시각"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="block_observations",
                        to="events.event",
                        verbose_name="일정",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_observations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="routines.routineblock",
                        verbose_name="블록",
                    ),
                ),
            ],
            options={
                "verbose_name": "블록 관측",
                "verbose_name_plural": "블록 관측",
                "db_table": "routines_block_observation",
                "ordering": ["-observed_on", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="routineblock",
            index=models.Index(
                fields=["user", "order"], name="routines_user_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="routineblock",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="routines_block_user_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="routineblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_min_minutes__lte", models.F("default_max_minutes"))
                ),
                name="routines_block_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_max_minutes__lte", 480)),
                name="routines_block_max_upper_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="routineblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("precondition", models.F("id")), _negated=True),
                name="routines_block_no_self_precondition",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventblockselection",
            constraint=models.UniqueConstraint(
                fields=("event", "block"), name="routines_selection_event_block_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="blockobservation",
            index=models.Index(
                fields=["user", "block"], name="routines_obs_user_block_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockobservation",
            index=models.Index(
                fields=["block", "observed_on"], name="routines_obs_block_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="blockobservation",
            constraint=models.UniqueConstraint(
                fields=("user", "client_uuid"),
                name="routines_obs_user_client_uuid_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="blockobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gte", 0)),
                name="routines_obs_duration_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="blockobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__lte", 480)),
                name="routines_obs_duration_upper_bound",
            ),
        ),
    ]
