# Generated by Django 5.2.16 on 2026-09-17 01:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=20, unique=True, verbose_name="키"),
                ),
                ("label", models.CharField(max_length=30, verbose_name="표시명")),
                (
                    "default_tau",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(0.999),
                        ],
                        verbose_name="기본 τ",
                    ),
                ),
                (
                    "penalty_shape",
                    models.CharField(
                        choices=[
                            ("step", "계단형 (1분만 늦어도 실패)"),
                            ("linear", "선형 (늦은 만큼 손해)"),
                        ],
                        max_length=10,
                        verbose_name="페널티 모양",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "일정 태그",
                "verbose_name_plural": "일정 태그",
                "db_table": "events_tag",
                "ordering": ["order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_tau__gte", 0.5), ("default_tau__lte", 0.999)
                        ),
                        name="events_tag_default_tau_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="장소명")),
                ("lat", models.FloatField(verbose_name="위도")),
                ("lng", models.FloatField(verbose_name="경도")),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="주소"),
                ),
                (
                    "kakao_place_id",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="카카오 장소 ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "장소",
                "verbose_name_plural": "장소",
                "db_table": "events_place",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lat__gte", -90), ("lat__lte", 90)),
                        name="events_place_lat_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lng__gte", -180), ("lng__lte", 180)),
                        name="events_place_lng_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "직접 입력"),
                            ("calendar", "캘린더 동기화"),
                            ("nlp", "자연어 파싱"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="출처",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="외부 ID"
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="제목")),
                ("start_at", models.DateTimeField(verbose_name="시작 시각")),
                (
                    "tau_override",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(0.999),
                        ],
                        verbose_name="τ 재지정",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.eventtag",
                        verbose_name="태그",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.place",
                        verbose_name="장소",
                    ),
                ),
            ],
            options={
                "verbose_name": "일정",
                "verbose_name_plural": "일정",
                "db_table": "events_event",
                "ordering": ["start_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_at"], name="events_user_start_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id__isnull", False)),
                        fields=("user", "external_id"),
                        name="events_event_user_external_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tau_override__isnull", True),
                            models.Q(
                                ("tau_override__gte", 0.5), ("tau_override__lte", 0.999)
                            ),
                            _connector="OR",
                        ),
                        name="events_event_tau_override_range",
                    ),
                ],
            },
        ),
    ]
