# Generated by Django 5.2.16 on 2026-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_seed_event_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="route_key",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="선택 경로"
            ),
        ),
    ]
