# Generated by Django 5.2.16 on 2026-09-21 07:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_route_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="origin_label",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="출발지 표시명"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="origin_lat",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="출발지 위도",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="origin_lng",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="출발지 경도",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin_lat__isnull", True), ("origin_lng__isnull", True)
                    ),
                    models.Q(
                        ("origin_lat__isnull", False), ("origin_lng__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="events_event_origin_pair",
            ),
        ),
    ]
