# Generated by Django 5.2.16 on 2026-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0004_event_origin_label_event_origin_lat_event_origin_lng_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="origin_label",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=80,
                verbose_name="출발지 표시명",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="route_key",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=120,
                verbose_name="선택 경로",
            ),
        ),
    ]
