# Generated by Django 5.2.16 on 2026-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_origin_label_alter_event_route_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alarm_enabled',
            field=models.BooleanField(blank=True, db_default=None, default=None, null=True, verbose_name='알람 켬/끔'),
        ),
    ]
