# Generated by Django 5.2.16 on 2026-09-16 15:28

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("nickname", models.CharField(max_length=20, verbose_name="닉네임")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="가입 시각"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
                "db_table": "accounts_user",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_lat",
                    models.FloatField(blank=True, null=True, verbose_name="집 위도"),
                ),
                (
                    "home_lng",
                    models.FloatField(blank=True, null=True, verbose_name="집 경도"),
                ),
                (
                    "home_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="집 표시명"
                    ),
                ),
                (
                    "default_tau",
                    models.FloatField(
                        default=0.9,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(0.999),
                        ],
                        verbose_name="기본 τ",
                    ),
                ),
                (
                    "onboarding_prep_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="온보딩 준비시간(분)"
                    ),
                ),
                (
                    "shadow_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="섀도 시작 시각"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Seoul", max_length=40, verbose_name="시간대"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로필",
                "verbose_name_plural": "프로필",
                "db_table": "accounts_profile",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_tau__gte", 0.5), ("default_tau__lte", 0.999)
                        ),
                        name="accounts_profile_default_tau_range",
                    )
                ],
            },
        ),
    ]
