# Generated by Django 5.2.16 on 2026-09-22 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_demo_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="home_lat",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="집 위도",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="home_lng",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="집 경도",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("home_lat__isnull", True),
                    models.Q(("home_lat__gte", -90), ("home_lat__lte", 90)),
                    _connector="OR",
                ),
                name="accounts_profile_home_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("home_lng__isnull", True),
                    models.Q(("home_lng__gte", -180), ("home_lng__lte", 180)),
                    _connector="OR",
                ),
                name="accounts_profile_home_lng_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("home_lat__isnull", True), ("home_lng__isnull", True)),
                    models.Q(("home_lat__isnull", False), ("home_lng__isnull", False)),
                    _connector="OR",
                ),
                name="accounts_profile_home_pair",
            ),
        ),
    ]
