# Generated by Django 5.2.16 on 2026-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_home_lat_alter_profile_home_lng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_agreed_at",
            field=models.DateTimeField(
                blank=True, db_default=None, default=None, null=True,
                verbose_name="약관 동의 시각",
            ),
        ),
    ]
