# Generated by Django 5.2.16 on 2026-09-17 01:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "계산 완료"),
                            ("no_home", "집 위치 미설정"),
                            ("no_place", "일정 장소 없음"),
                            ("route_failed", "경로 조회 실패"),
                        ],
                        default="ok",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                (
                    "alarm_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="알람 시각"
                    ),
                ),
                (
                    "depart_by",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="출발 시각"
                    ),
                ),
                (
                    "arrive_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="도착 예정"
                    ),
                ),
                (
                    "prep_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="준비 시간(분)"
                    ),
                ),
                (
                    "travel_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="이동 시간(분)"
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="안전 버퍼(분)"
                    ),
                ),
                (
                    "tau_used",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(0.999),
                        ],
                        verbose_name="적용 τ",
                    ),
                ),
                (
                    "on_time_probability",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="정시 도착 확률(%)",
                    ),
                ),
                (
                    "travel_mode",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="이동 수단"
                    ),
                ),
                (
                    "travel_source",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="이동시간 출처"
                    ),
                ),
                (
                    "route_summary",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="경로 요약"
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="계산 시각"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_plan",
                        to="events.event",
                        verbose_name="일정",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알람 계획",
                "verbose_name_plural": "알람 계획",
                "db_table": "planning_alarm_plan",
                "indexes": [
                    models.Index(
                        fields=["user", "alarm_at"], name="plan_user_alarm_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "ok"), _negated=True),
                            models.Q(
                                ("alarm_at__isnull", False),
                                ("depart_by__isnull", False),
                                ("arrive_at__isnull", False),
                                ("prep_minutes__isnull", False),
                                ("travel_minutes__isnull", False),
                                ("buffer_minutes__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="planning_plan_ok_requires_values",
                    )
                ],
            },
        ),
    ]
