# Generated by Django 5.2.16 on 2026-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmplan",
            name="route_detail",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="경로 상세"
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="route_key",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="사용한 경로"
            ),
        ),
    ]
