# Generated by Django 5.2.16 on 2026-09-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alarmplan_route_detail_alarmplan_route_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmplan",
            name="confidence_basis",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="확신도 근거"
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="prep_breakdown",
            field=models.JSONField(blank=True, default=list, verbose_name="준비 내역"),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="prep_source",
            field=models.CharField(
                blank=True, default="", max_length=24, verbose_name="준비시간 출처"
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="total_quantile_minutes",
            field=models.FloatField(
                blank=True, null=True, verbose_name="합성 분위수(분)"
            ),
        ),
    ]
