# Generated by Django 5.2.16 on 2026-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planning",
            "0003_alarmplan_confidence_basis_alarmplan_prep_breakdown_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmplan",
            name="confidence_basis",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=32,
                verbose_name="확신도 근거",
            ),
        ),
        migrations.AlterField(
            model_name="alarmplan",
            name="prep_breakdown",
            field=models.JSONField(
                blank=True,
                db_default=models.Value("[]", output_field=models.JSONField()),
                default=list,
                verbose_name="준비 내역",
            ),
        ),
        migrations.AlterField(
            model_name="alarmplan",
            name="prep_source",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=24,
                verbose_name="준비시간 출처",
            ),
        ),
    ]
