# Generated by Django 5.2.16 on 2026-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0004_alter_alarmplan_confidence_basis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarmplan",
            name="route_detail",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=120,
                verbose_name="경로 상세",
            ),
        ),
        migrations.AlterField(
            model_name="alarmplan",
            name="route_key",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=120,
                verbose_name="사용한 경로",
            ),
        ),
    ]
