# Generated by Django 5.2.16 on 2026-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0005_alter_alarmplan_route_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmplan",
            name="route_distance_m",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="경로 길이(m)"
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="route_path",
            field=models.JSONField(
                blank=True,
                db_default=models.Value("[]", output_field=models.JSONField()),
                default=list,
                verbose_name="경로 좌표",
            ),
        ),
    ]
