# Generated by Django 5.2.16 on 2026-09-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0007_alter_alarmplan_prep_breakdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmplan",
            name="alt_faster_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="더 빠른 정도(분)"
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="alt_route_key",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=120,
                verbose_name="더 빠른 경로",
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="alt_route_label",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=120,
                verbose_name="더 빠른 경로 이름",
            ),
        ),
        migrations.AddField(
            model_name="alarmplan",
            name="alt_route_path",
            field=models.JSONField(
                blank=True,
                db_default=models.Value([], output_field=models.JSONField()),
                default=list,
                verbose_name="더 빠른 경로 좌표",
            ),
        ),
    ]
