# Generated by Django 5.2.16 on 2026-09-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_event_route_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TripObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("depart", "출발"), ("arrive", "도착")],
                        max_length=10,
                        verbose_name="종류",
                    ),
                ),
                (
                    "detector",
                    models.CharField(
                        choices=[("gps", "GPS 반경 판정"), ("manual", "직접 입력")],
                        default="gps",
                        max_length=10,
                        verbose_name="판별기",
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="관측 시각")),
                ("lat", models.FloatField(verbose_name="위도")),
                ("lng", models.FloatField(verbose_name="경도")),
                ("accuracy_m", models.FloatField(verbose_name="위치 정확도(m)")),
                ("distance_m", models.FloatField(verbose_name="기준점까지 거리(m)")),
                (
                    "client_uuid",
                    models.CharField(max_length=40, verbose_name="클라이언트 UUID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시각"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_observations",
                        to="events.event",
                        verbose_name="일정",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_observations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "이동 관측",
                "verbose_name_plural": "이동 관측",
                "db_table": "observations_trip",
                "ordering": ["-observed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "observed_at"], name="obs_user_observed_idx"
                    ),
                    models.Index(fields=["event", "kind"], name="obs_event_kind_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "client_uuid"),
                        name="obs_user_client_uuid_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lat__gte", -90), ("lat__lte", 90)),
                        name="obs_lat_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lng__gte", -180), ("lng__lte", 180)),
                        name="obs_lng_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("accuracy_m__gte", 0)),
                        name="obs_accuracy_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("distance_m__gte", 0)),
                        name="obs_distance_nonneg",
                    ),
                ],
            },
        ),
    ]
