# Generated by Django 5.2.16 on 2026-09-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripobservation",
            name="dwell_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="체류 시간(초)"
            ),
        ),
    ]
